### ISSUE TITLE
KeyError: 'Unable to open object (Component not found)'

### ISSUE THREAD

**Issue by petteriTeikari** [petteriTeikari/vesselNN#1]
Problem with opening the .h5 files

```
stdpre:  /
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main( args )
  File "train.py", line 69, in main
    net, lc = znetio.create_net(pars)
  File "/home/petteri/testVesselNN/vesselNN/znn-release/python/front_end/znetio.py", line 454, in create_net
    lc = zstatistics.CLearnCurve( fnet )
  File "/home/petteri/testVesselNN/vesselNN/znn-release/python/zstatistics.py", line 28, in __init__
    self._read_curve( fname )
  File "/home/petteri/testVesselNN/vesselNN/znn-release/python/zstatistics.py", line 49, in _read_curve
    self.tt_it  = list( f[self.stdpre + 'test/it'].value )
  File "_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2511)
  File "_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2464)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2511)
  File "_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2464)
  File "h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip_build_root/h5py/h5py/h5o.c:3556)
KeyError: 'Unable to open object (Component not found)'
```

**Comment by xxdiablo** [comment]
Have you solved this problem?

**Comment by petteriTeikari** [comment]
Unfortunately not @xxdiablo, the whole repo should be rebuilt and I had hopes for immigrating to another framework when I had the time
