### ISSUE TITLE
AttributeError: 'module' object has no attribute 'emio'

### ISSUE THREAD

**Issue by kkhuang1990** [petteriTeikari/vesselNN#2]
when I run the command below to train the model
python train.py -c ../../configs/ZNN_configs/config_VD2D_tanh.cfg
error like this came out
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main( args )
  File "train.py", line 77, in main
    smp_trn = zsample.CSamples(config, pars, pars['train_range'], net, outsz, logfile)
  File "/home/mil/huang/Coronary_Artery_Segmentation/vesselNN/znn-release/python/front_end/zsample.py", line 551, in __init__
    sample = CBoundarySample(config, pars, sid, net, outsz, log)
  File "/home/mil/huang/Coronary_Artery_Segmentation/vesselNN/znn-release/python/front_end/zsample.py", line 422, in __init__
    log=log, is_forward=is_forward)
  File "/home/mil/huang/Coronary_Artery_Segmentation/vesselNN/znn-release/python/front_end/zsample.py", line 58, in __init__
    outsz, setsz_in, fov, is_forward=is_forward )
  File "/home/mil/huang/Coronary_Artery_Segmentation/vesselNN/znn-release/python/front_end/zdataset.py", line 377, in __init__
    outsz, setsz, mapsz, is_forward=is_forward )
  File "/home/mil/huang/Coronary_Artery_Segmentation/vesselNN/znn-release/python/front_end/zdataset.py", line 229, in __init__
    arrlist = self._read_files( fnames );
  File "/home/mil/huang/Coronary_Artery_Segmentation/vesselNN/znn-release/python/front_end/zdataset.py", line 305, in _read_files
    vol = emirt.emio.imread(fl)
AttributeError: 'module' object has no attribute 'emio'

I have already downloaded the latest emirt from github and put it under the znn-release/python dir

**Comment by petteriTeikari** [comment]
Yes the external dependencies are a bit tricky, or can be @kkhuang1990 :S

I think it would be interesting to try the dataset, and the same basic architecture with that DeepMedic for example: https://github.com/Kamnitsask/deepmedic

Or convert the simple 2D+3D into a residual architecture? And as Theano gets discontinued, maybe implement the whole thing from scratch using Tensorflow or PyTorch?

Or just having to redo the configs and all based on the latest code from ZNN guys if you want more memory without the GPU acceleration?
https://github.com/seung-lab/znn-release
